### ISSUE TITLE
Perubahan Navbar 🎯

### ISSUE THREAD

**Issue by panntod** [Rizalramzi/treadwear.co#7]
Tambahkan element Anchor pada navbar supaya mempermudah navigasi antar page, dari seperti ini:

```
<ul class="flex flex-col gap-[7.442vw] text-black font-semibold text-[4.186vw] mt-[4.884vw]">
   <li>Collection</li>
   <li>Product</li>
   <li>Blog</li>
   <li>Store Location</li>
</ul>
```

menjadi seperti ini:

```
<ul class="flex flex-col gap-[7.442vw] text-black font-semibold text-[4.186vw] mt-[4.884vw]">
   <li><a href="#">Collection</a></li>
   <li><a href="#">Product</a></li>
   <li><a href="#">Blog</a></li>
   <li><a href="#">Store Location</a></li>
</ul>
```

*Note: Perlu menambahkan beberapa style, seperti text-decoration: none; untuk menghilangkan underline

**Comment by Rizalramzi** [comment]
Halo Selamat Malam kak Pandhu!

Terimakasih sudah mengunjungi website kami, untuk navbar sudah kami perbaiki sesuai dengan saran yang diberikan!

Salam hangat, Rizalramzi :)
